-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Aug 23, 2019 at 11:21 PM
-- Server version: 5.5.61-cll
-- PHP Version: 7.2.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `x28crvnc_formular`
--

-- --------------------------------------------------------

--
-- Table structure for table `formular`
--

CREATE TABLE `formular` (
  `id` int(11) NOT NULL,
  `name` varchar(250) NOT NULL,
  `asigurat` varchar(250) NOT NULL,
  `varsta` varchar(250) NOT NULL,
  `datanasterii` varchar(250) NOT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `sex` varchar(255) DEFAULT NULL,
  `Adresa` varchar(255) DEFAULT NULL,
  `Localitate` varchar(255) DEFAULT NULL,
  `Judet` varchar(255) DEFAULT NULL,
  `Talie` varchar(255) DEFAULT NULL,
  `Greutate` varchar(255) DEFAULT NULL,
  `Circumferinta_abdominala` varchar(255) DEFAULT NULL,
  `Circumferinta_soldurilor` varchar(255) DEFAULT NULL,
  `Tensiunea_arteriala_ortostatism` varchar(255) DEFAULT NULL,
  `Tensiunea_arteriala_clinostatism` varchar(255) DEFAULT NULL,
  `acuze` varchar(255) DEFAULT NULL,
  `Antecedente_heredo_colaterale` varchar(255) DEFAULT NULL,
  `antecedente_fiziologice` varchar(255) DEFAULT NULL,
  `Antecedente_personale_fiziologice` varchar(255) DEFAULT NULL,
  `numar_nasteri` varchar(255) DEFAULT NULL,
  `numar_sarcini` varchar(255) DEFAULT NULL,
  `numar_avorturi` varchar(255) DEFAULT NULL,
  `antecedente_patologice` varchar(255) DEFAULT NULL,
  `tip_dz` varchar(255) DEFAULT NULL,
  `grad_hta` varchar(255) DEFAULT NULL,
  `antecedente_personale_patologice` varchar(255) DEFAULT NULL,
  `medicatia_curenta` varchar(255) DEFAULT NULL,
  `loc_munca` varchar(255) DEFAULT NULL,
  `fumator` varchar(255) DEFAULT NULL,
  `pachete_an` varchar(255) DEFAULT NULL,
  `an_nefumator` varchar(255) DEFAULT NULL,
  `mese_zi` varchar(255) DEFAULT NULL,
  `legume` varchar(255) DEFAULT NULL,
  `fructe` varchar(255) DEFAULT NULL,
  `lactate` varchar(255) DEFAULT NULL,
  `fainoase` varchar(255) DEFAULT NULL,
  `proteine` varchar(255) DEFAULT NULL,
  `ml_alcool` varchar(255) DEFAULT NULL,
  `alcool_zi` varchar(255) DEFAULT NULL,
  `suplimente` varchar(255) DEFAULT NULL,
  `tegumente_mucoase_fanere` varchar(255) DEFAULT NULL,
  `observatii_tegumente` varchar(255) DEFAULT NULL,
  `tesut_conjuctiv_adipos` varchar(255) DEFAULT NULL,
  `observatii_tesut` varchar(255) DEFAULT NULL,
  `sistem_ganglionar` varchar(255) DEFAULT NULL,
  `observatii_ganglionar` varchar(255) DEFAULT NULL,
  `muscular_osteo_articular` varchar(255) DEFAULT NULL,
  `observatii_muscular` varchar(255) DEFAULT NULL,
  `aparat_respirator` varchar(255) DEFAULT NULL,
  `observatii_aparat_respirator` varchar(255) DEFAULT NULL,
  `aparat_cardiovascular` varchar(255) DEFAULT NULL,
  `observatii_cardiovascular` varchar(255) DEFAULT NULL,
  `abdomen` varchar(255) DEFAULT NULL,
  `observatii_abdomen` varchar(255) DEFAULT NULL,
  `ficat_bila_splina` varchar(255) DEFAULT NULL,
  `observatii_ficat` varchar(255) DEFAULT NULL,
  `aparat_genito_urinar` varchar(255) DEFAULT NULL,
  `observatii_genito_urinar` varchar(255) DEFAULT NULL,
  `sistem_nervos` varchar(255) DEFAULT NULL,
  `observatii_sistem_nervos` varchar(255) DEFAULT NULL,
  `organe_de_simt` varchar(255) DEFAULT NULL,
  `observatii_organe_de_simt` varchar(255) DEFAULT NULL,
  `tiroida` varchar(255) DEFAULT NULL,
  `observatii_tiroida` varchar(255) DEFAULT NULL,
  `consultari_suplimentare` varchar(255) DEFAULT NULL,
  `alte_consulturi` varchar(255) DEFAULT NULL,
  `diagnostice` varchar(255) DEFAULT NULL,
  `recomandari` varchar(255) DEFAULT NULL,
  `doctor` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `diagnostice_vechi` varchar(255) DEFAULT NULL,
  `diagnostice_noi` varchar(255) DEFAULT NULL,
  `observatii_diagnostice_noi` varchar(255) DEFAULT NULL,
  `observatii_diagnostice_vechi` varchar(255) DEFAULT NULL,
  `bilant_clinic` varchar(255) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `formular`
--

INSERT INTO `formular` (`id`, `name`, `asigurat`, `varsta`, `datanasterii`, `phone`, `sex`, `Adresa`, `Localitate`, `Judet`, `Talie`, `Greutate`, `Circumferinta_abdominala`, `Circumferinta_soldurilor`, `Tensiunea_arteriala_ortostatism`, `Tensiunea_arteriala_clinostatism`, `acuze`, `Antecedente_heredo_colaterale`, `antecedente_fiziologice`, `Antecedente_personale_fiziologice`, `numar_nasteri`, `numar_sarcini`, `numar_avorturi`, `antecedente_patologice`, `tip_dz`, `grad_hta`, `antecedente_personale_patologice`, `medicatia_curenta`, `loc_munca`, `fumator`, `pachete_an`, `an_nefumator`, `mese_zi`, `legume`, `fructe`, `lactate`, `fainoase`, `proteine`, `ml_alcool`, `alcool_zi`, `suplimente`, `tegumente_mucoase_fanere`, `observatii_tegumente`, `tesut_conjuctiv_adipos`, `observatii_tesut`, `sistem_ganglionar`, `observatii_ganglionar`, `muscular_osteo_articular`, `observatii_muscular`, `aparat_respirator`, `observatii_aparat_respirator`, `aparat_cardiovascular`, `observatii_cardiovascular`, `abdomen`, `observatii_abdomen`, `ficat_bila_splina`, `observatii_ficat`, `aparat_genito_urinar`, `observatii_genito_urinar`, `sistem_nervos`, `observatii_sistem_nervos`, `organe_de_simt`, `observatii_organe_de_simt`, `tiroida`, `observatii_tiroida`, `consultari_suplimentare`, `alte_consulturi`, `diagnostice`, `recomandari`, `doctor`, `status`, `diagnostice_vechi`, `diagnostice_noi`, `observatii_diagnostice_noi`, `observatii_diagnostice_vechi`, `bilant_clinic`) VALUES
(102, 'Bogdan Incrosnatu', 'Asigurat', '23', '23123', '733131284', 'F', NULL, 'Craiova', '212r21r', '140', '140', '140', '140', '23', '23', '', '', NULL, '', '', '', '', NULL, '', '', NULL, '', 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', 'zzseen', NULL, NULL, '', '', 'clinic_sanatos'),
(101, 'Bajan Aurica ', 'Asigurat', '61', '26.06.1992', '', 'frontdesk_uitat', NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '3', NULL, '', 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', 'zzseen', NULL, NULL, '', 'HTA ', 'clinic_sanatos'),
(100, 'Bajan Aurica - test', 'Asigurat', '61', '26.06.1992', 'aadvsava', 'frontdesk_uitat', NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '', NULL, '', 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', 'zzseen', NULL, 'status_supraponderal, obezitate_grad_1, obezitate_grad_2', '', 'HTA ', 'clinic_sanatos'),
(99, 'Bajan Aurica ', 'Asigurat', '61', '26.06.1992', '', NULL, NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '3', NULL, NULL, 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', '', NULL, NULL, '', 'HTA ', 'clinic_sanatos'),
(98, 'Bajan Aurica - test', 'Asigurat', '61', '26.06.1992', 'aadvsava', NULL, NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '', NULL, NULL, 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', '', NULL, NULL, '', 'HTA ', 'clinic_sanatos'),
(97, 'Bogdan Incrosnatu', 'Asigurat', '23', '23123', '733131284', 'F', NULL, 'Craiova', '212r21r', '140', '140', '140', '140', '23', '23', '', '', NULL, '', '', '', '', NULL, '', '', NULL, '', 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', 'zzseen', NULL, NULL, '', '', 'clinic_sanatos'),
(96, 'Bajan Aurica ', 'Asigurat', '61', '26.06.1992', '', 'frontdesk_uitat', NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '3', NULL, '', 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', 'zzseen', NULL, NULL, '', 'HTA ', 'clinic_sanatos'),
(95, 'Bajan Aurica - test', 'Asigurat', '61', '26.06.1992', 'aadvsava', 'frontdesk_uitat', NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '', NULL, '', 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', 'zzseen', NULL, 'status_supraponderal, obezitate_grad_1, obezitate_grad_2', '', 'HTA ', 'clinic_sanatos'),
(94, 'Bajan Aurica ', 'Asigurat', '61', '26.06.1992', '', NULL, NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '3', NULL, NULL, 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', '', NULL, NULL, '', 'HTA ', 'clinic_sanatos'),
(93, 'Bajan Aurica - test', 'Asigurat', '61', '26.06.1992', 'aadvsava', NULL, NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '', NULL, NULL, 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', '', NULL, NULL, '', 'HTA ', 'clinic_sanatos'),
(92, 'Bogdan Incrosnatu', 'Asigurat', '23', '23123', '733131284', 'F', NULL, 'Craiova', '212r21r', '140', '140', '140', '140', '23', '23', '', '', NULL, '', '', '', '', NULL, '', '', NULL, '', 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', 'zzseen', NULL, NULL, '', '', 'clinic_sanatos'),
(91, 'Bajan Aurica ', 'Asigurat', '61', '26.06.1992', '', 'frontdesk_uitat', NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '3', NULL, '', 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', 'zzseen', NULL, NULL, '', 'HTA ', 'clinic_sanatos'),
(90, 'Bajan Aurica - test', 'Asigurat', '61', '26.06.1992', 'aadvsava', 'frontdesk_uitat', NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '', NULL, '', 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', 'zzseen', NULL, 'status_supraponderal, obezitate_grad_1, obezitate_grad_2', '', 'HTA ', 'clinic_sanatos'),
(88, 'Bajan Aurica - test', 'Asigurat', '61', '26.06.1992', 'aadvsava', NULL, NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '', NULL, NULL, 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', '', NULL, NULL, '', 'HTA ', 'clinic_sanatos'),
(89, 'Bajan Aurica ', 'Asigurat', '61', '26.06.1992', '', NULL, NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '3', NULL, NULL, 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', '', NULL, NULL, '', 'HTA ', 'clinic_sanatos'),
(103, 'Adina giba 2', 'Asigurat', '67', '67.08.2009', '0766566122', 'frontdesk_uitat', NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, '', 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(104, 'Adina giba 2', 'Asigurat', '67', '67.08.2009', '0766566122', NULL, NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(105, 'Adina giba', 'Neasigurat', '19', '90.56.2009', '0765122098', NULL, NULL, 'Tg. Frumos', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(106, 'Agnes Iacob', 'Neasigurat', '34', '78.09.2004', '0455088071', NULL, NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(107, 'Agnes iacob', 'Neasigurat', '89', '56.09.1234', '0987444666', NULL, NULL, 'Buc', 'Ilf', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(108, 'Alina jj 1', 'Asigurat', '43', '34.12.3301', '0990122334', NULL, NULL, 'Cc', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(109, 'Alina jj 2', 'Asigurat', '66', '34.02.2001', '0776455665', NULL, NULL, 'Barlad', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(110, 'Anca luca 1 ', 'Asigurat', '34', '43.67.9008', '0997456123', NULL, NULL, 'Hlincea', 'Is', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(111, 'Anca luca 2', 'Neasigurat', '54', '12.09.3008', '6754129087', NULL, NULL, 'Barnova', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(112, 'Anca stefan', 'Asigurat', '66', '78.09.1235', '0765345092', NULL, NULL, 'Moin', 'Bc', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(113, 'Andree abuzi 2', 'Asigurat', '66', '78.09.2005', '0745099011', NULL, NULL, 'Savinesti', 'Botosani', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(114, 'Andreea abuziloae', 'Asigurat', '90', '07.09.3305', '7881033788', NULL, NULL, 'Iasi', 'Botosani', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(115, 'Bajan Aurica - test', 'Asigurat', '61', '26.06.1992', 'aadvsava', NULL, NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '', NULL, NULL, 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', '', NULL, NULL, '', 'HTA ', 'clinic_sanatos'),
(116, 'Bajan Aurica ', 'Asigurat', '61', '26.06.1992', '', 'frontdesk_uitat', NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '', NULL, '', 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', '', NULL, NULL, '', 'HTA ', 'clinic_sanatos'),
(117, 'Bajan Aurica ', 'Asigurat', '61', '26.06.1992', '', NULL, NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '3', NULL, NULL, 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', '', NULL, NULL, '', 'HTA ', 'clinic_sanatos'),
(118, 'Bogdan Agavriloaiei 1', 'Asigurat', '22', '12/12/2012', '733131284', NULL, NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(119, 'Bogdan Agavriloaiei 2', 'Asigurat', '22', '12/12/2012', '733131284', NULL, NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, '', 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(120, 'Bogdan Incrosnatu', 'Asigurat', '11', '12/12/2012', '733131284', NULL, NULL, 'Craiova', '', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(121, 'Burlacu Diana', 'frontdesk_uitat', '67', '54.03.2009', '9007655123', NULL, NULL, 'bacau', 'Bc', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(122, 'Corin varlam 2', 'Asigurat', '66', '67.54.3334', '0887445667', NULL, NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(123, 'Corina varlam 1', 'Asigurat', '11', '98.45.1221', '0665122667', NULL, NULL, 'Poieni', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(124, 'Delia Padurariu 1', 'Asigurat', '22', '12/12/2012', '733131284', NULL, NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(125, 'Delia Padurariu 2', 'Asigurat', '22', '12/12/2012', '733131284', NULL, NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(126, 'Diana burlacu 2', 'frontdesk_uitat', '76', '98.02.1998', '7896345765', NULL, NULL, 'Yassy', 'Bc', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(127, 'Eliza Mititelu 2', 'Asigurat', '76', '55.09.2001', '5671344099', NULL, NULL, 'Ciresoaia', 'Bc', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(128, 'Eliza mititelu 2', 'Neasigurat', '57', '09.65.2090', '8765098123', NULL, NULL, '', '', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(129, 'Eliza tofan 2', 'Asigurat', '6', '56.09.2001', '0744099065', NULL, NULL, 'Vaslooi', 'Vs', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(130, 'Eliza tofan', 'Asigurat', '77', '67.04.1003', '0855099034', NULL, NULL, 'Vaslui', 'Vs', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(131, 'Georgiana Tofan 1', 'Asigurat', '22', '12/12/2012', '733131284', NULL, NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(132, 'Georgiana Tofan 2', 'Asigurat', '22', '12/12/2012', '733131284', NULL, NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(133, 'Laura mitrofan 1', 'Neasigurat', '67', '67.98.9001', '6556890567', NULL, NULL, 'Iqai', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(134, 'Laura mitrofan 2', 'Asigurat', '44', '90.56.2200', '678123467', NULL, NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(135, 'Lorena Mihaita 1', 'Asigurat', '22', '12/12/2012', '733131284', NULL, NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(136, 'Lorena Mihaita 2', 'Asigurat', '22', '12/12/2012', '733131284', NULL, NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(137, 'Mihaela florea 1', 'Asigurat', '54', '67.65.3304', '7889543665', NULL, NULL, 'Harlau', 'Constanta', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(138, 'Mihaela florea 2', 'Asigurat', '33', '44.23.8989', '0556433166', NULL, NULL, 'Aroneanu', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(139, 'Mititelu eliza', 'frontdesk_uitat', '66', '45.32.0912', '0987456123', NULL, NULL, 'Ciresoaia', 'Bc', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(140, 'Pdu ', 'frontdesk_uitat', '', '', '', 'frontdesk_uitat', NULL, '', '', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, '', 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(141, 'Pdu 1', 'Asigurat', '55', '17.09.7777', '6583098178', 'frontdesk_uitat', NULL, 'Iasi', 'Iasi', '100', '100', '100', '100', '140', '140', 'Durere hipocondru drept', 'Tata ima', NULL, '', '0', '0', '0', NULL, '', '', NULL, 'Antihipertensive', 'Non_Toxic', 'Da_trecut', '', '6', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'normal_reprezentat, exces, slab_reprezentat', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', '', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', '', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', 'fara_consulturi', '', NULL, 'FÄƒrÄƒ recomandÄƒri om sanatos', 'Pdutz', '', 'obezitate_grad_1, obezitate_grad_2, obezitate_morbida', 'HTA_grad_1_risc_scazut, HTA_grad_1_risc_inalt, HTA_grad_2_risc_inalt', 'Doar hta', 'Obezitateeee', 'recomandare_consult_MF'),
(142, 'Pdu 1', 'Asigurat', '19', '34.89.1994', '5643876123', 'M', NULL, 'Iasi', 'Iasi', '90', '90', '90', '90', '90', '90', 'Nada', 'Nadaaa', NULL, '', '0', '0', '0', NULL, '', '', NULL, 'Fara pastile', 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'normal_reprezentat, exces, slab_reprezentat', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', '', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', '', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'normal, tiroida_palpabila, consistenta_elastica', '', 'fara_consulturi', '', NULL, 'Pisici', 'PduÈ›', '', 'obezitate_grad_1, obezitate_grad_2, obezitate_morbida', 'obezitate_grad_1, obezitate_grad_2, obezitate_morbida', 'Obezzz', 'OBezj', 'clinic_sanatos'),
(143, 'Pdu 2', 'Neasigurat', '89', '56.8i.2000', '5678432890', 'M', NULL, 'Iasi', 'Iasi', '10', '10', '10', '10', '200', '100', 'Durere abdominala difuza', 'Ffff multe', NULL, '', '10', '12', '2', 'HTA, DZ, BAP, BCR', '6', '4', NULL, 'F multe pastile colorate', 'Non_Toxic', 'Da_trecut', '15', '16', NULL, NULL, NULL, NULL, NULL, NULL, '4000', '15', NULL, 'facies_normal, pliu_elastic, mucoase_normale, fanere_normale', 'Pletoric facies', 'normal_reprezentat, exces, slab_reprezentat', '            Obeza rau', NULL, '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'torace_normal, ampliatii_normale, sonoritate_normala', 'Mv abolit -ish', 'soc_apexian, pulsuri_periferice_palpabile', 'Suflu sistolic de im', 'zgomote_intestinale_prezente, fara_semne_iritatie, aspect_scaun_normal', 'Grasutza', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', NULL, 'Giordano +', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'normal, tiroida_palpabila, consistenta_elastica', '', 'consult_medicina_interna, consult_dermatologie, consult_oftalmologie', 'Pedi', NULL, 'Dieta\r\nPastile\r\nCordarone', 'Pdoo', '', 'status_supraponderal, obezitate_grad_2', 'consult_dermatologie, consult_oftalmologie', '', '', 'urgenta_medicala'),
(144, 'Razvan Ciocan 1', 'Asigurat', '22', '12/12/2012', '0733131284', NULL, NULL, 'Iasi', 'Ialomita', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(145, 'Razvan Ciocan 2', 'Neasigurat', '22', '12/12/2012', '733131284', NULL, NULL, 'Craiova', 'dasdsadsa', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos');
INSERT INTO `formular` (`id`, `name`, `asigurat`, `varsta`, `datanasterii`, `phone`, `sex`, `Adresa`, `Localitate`, `Judet`, `Talie`, `Greutate`, `Circumferinta_abdominala`, `Circumferinta_soldurilor`, `Tensiunea_arteriala_ortostatism`, `Tensiunea_arteriala_clinostatism`, `acuze`, `Antecedente_heredo_colaterale`, `antecedente_fiziologice`, `Antecedente_personale_fiziologice`, `numar_nasteri`, `numar_sarcini`, `numar_avorturi`, `antecedente_patologice`, `tip_dz`, `grad_hta`, `antecedente_personale_patologice`, `medicatia_curenta`, `loc_munca`, `fumator`, `pachete_an`, `an_nefumator`, `mese_zi`, `legume`, `fructe`, `lactate`, `fainoase`, `proteine`, `ml_alcool`, `alcool_zi`, `suplimente`, `tegumente_mucoase_fanere`, `observatii_tegumente`, `tesut_conjuctiv_adipos`, `observatii_tesut`, `sistem_ganglionar`, `observatii_ganglionar`, `muscular_osteo_articular`, `observatii_muscular`, `aparat_respirator`, `observatii_aparat_respirator`, `aparat_cardiovascular`, `observatii_cardiovascular`, `abdomen`, `observatii_abdomen`, `ficat_bila_splina`, `observatii_ficat`, `aparat_genito_urinar`, `observatii_genito_urinar`, `sistem_nervos`, `observatii_sistem_nervos`, `organe_de_simt`, `observatii_organe_de_simt`, `tiroida`, `observatii_tiroida`, `consultari_suplimentare`, `alte_consulturi`, `diagnostice`, `recomandari`, `doctor`, `status`, `diagnostice_vechi`, `diagnostice_noi`, `observatii_diagnostice_noi`, `observatii_diagnostice_vechi`, `bilant_clinic`) VALUES
(146, 'Stefan anca 1', 'frontdesk_uitat', '66', '12.09.3340', '876123098', NULL, NULL, 'Moinesti ', 'Moinesti', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(147, 'Teo Serban 1', 'Neasigurat', '22', '12/12/2012', '733131284', NULL, NULL, 'Craiova', 'dasdsadsa', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(148, 'Teo Serban 2', 'Neasigurat', '22', '12/12/2012', '733131284', NULL, NULL, 'Craiova', 'dasdsadsa', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(149, 'Vlad Brb 1', 'Neasigurat', '22', '12/12/2012', '0733131284', NULL, NULL, 'BuCuresti', 'Bucuresti', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(150, 'Vlad Brb 2', 'Neasigurat', '22', '12/12/2012', '733131284', NULL, NULL, 'Craiova', 'Dolj', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(151, 'Vlad Gheorghiu 1', 'Asigurat', '24', '12/12/2012', '0733456789', NULL, NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(152, 'Vlad Gheorghiu 2', 'Asigurat', '22', '12/12/2012', '0733456789', NULL, NULL, 'Iasi', 'Iasi', '', '', '', '', '', '', '', '', NULL, '', '', '', '', NULL, '', '', NULL, NULL, 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', '', NULL, NULL, '', '', 'clinic_sanatos'),
(153, 'Bajan Aurica ', 'Asigurat', '61', '26.06.1992', '', 'frontdesk_uitat', NULL, '', '', '156', '68', '93', '109', '153 dr 144 stg.', '91 dr 90 stg', 'Dueri toracice caracter de junghi stangi si drepte 5 minute \r\nPirozis \r\n', 'Probabil avc mama ', NULL, '', '6', '6', '0', 'HTA', '', '3', NULL, '', 'Non_Toxic', 'Nu', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'exces', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', 'Mv usor inasprit fara zgomote supraadaugate', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', 'Av 89', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', NULL, '', NULL, '', '', 'zzseen', NULL, NULL, '', 'HTA ', 'clinic_sanatos'),
(154, 'Bogdan Incrosnatu', 'Asigurat', '23', '23123', '733131284', 'F', NULL, 'Craiova', '212r21r', '140', '140', '140', '140', '23', '23', '', '', NULL, '', '', '', '', NULL, '', '', NULL, '', 'frontdesk_uitat', 'frontdesk_uitat', '', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, NULL, '', NULL, '            ', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', '', 'zzseen', NULL, NULL, '', '', 'clinic_sanatos'),
(155, 'Pdu 1', 'Asigurat', '55', '17.09.7777', '6583098178', 'frontdesk_uitat', NULL, 'Iasi', 'Iasi', '100', '100', '100', '100', '140', '140', 'Durere hipocondru drept', 'Tata ima', NULL, '', '0', '0', '0', NULL, '', '', NULL, 'Antihipertensive', 'Non_Toxic', 'Da_trecut', '', '6', NULL, NULL, NULL, NULL, NULL, NULL, '', '', NULL, 'normale, facies_normal, tegument_normal, pliu_elastic, mucoase_normale, fanere_normale, fara_leziuni', '', 'normal_reprezentat, exces, slab_reprezentat', '            ', 'NORMALE, fara_adenopatii_palpabile', '', 'normal, facies_normal, muscular_normotrof_normoton, osteo_articular_integru', '', 'normal, torace_normal, tegument_normal, ampliatii_normale, sonoritate_normala, murmur_vezicular_egal_bilateral', '', 'normal, soc_apexian, zgomote_cardiace_echipotente, pulsuri_periferice_palpabile', '', 'normal, abdomen_suplu, zgomote_intestinale_prezente, fara_mase_intraabdominale, fara_semne_iritatie, tranzit_intestinal_prezent, aspect_scaun_normal', '', 'normal, ficat_palbabil_rebordul_costal, colecist_nepalpabil, splina_nepalpabila', '', 'normal, mitiuni_fiziologice, giordano_negativ, rinichi_nepalpabili, vezica_urinara_nepalpabila, zone_anexiale_suple, glande_mamare_normale', '', 'normal, pacient_constient_cooperant, nervii_cranieni_intacti, fara_semne_neurologice_focar, fara_tulburari_psihice', '', 'normal, acuitate_vizuala_normala, acuitate_auditiva_normala, fara_tulburari_senzitive_cutanate', '', 'tiroida_palpabila, consistenta_elastica', '', 'fara_consulturi', '', NULL, 'FÄƒrÄƒ recomandÄƒri om sanatos', 'Pdutz', 'zzseen', 'obezitate_grad_1, obezitate_grad_2, obezitate_morbida', 'HTA_grad_1_risc_scazut, HTA_grad_1_risc_inalt, HTA_grad_2_risc_inalt', 'Doar hta', 'Obezitateeee', 'recomandare_consult_MF');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `formular`
--
ALTER TABLE `formular`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `formular`
--
ALTER TABLE `formular`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=156;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
